### ISSUE TITLE
[PyroCMS 3] Cannot install when debug is true

### ISSUE THREAD

**Issue by bloveless** [pyrocms/pyrocms#3555]
There are some javascript issues when debug is set to true and attempting to install.

<img width="1440" alt="screen shot 2015-10-26 at 9 59 25 am" src="https://cloud.githubusercontent.com/assets/535135/10734425/cd2a64c8-7bc8-11e5-93c7-94aad83005a5.png">

This is from the log.

```
[2015-10-26 15:59:22] local.ERROR: exception 'ErrorException' with message 'Undefined index: database_driver' in /Users/brennon/Projects/php/pyrocms.dev/core/anomaly/installer-module/src/InstallerModuleInstaller.php:34
Stack trace:
#0 /Users/brennon/Projects/php/pyrocms.dev/core/anomaly/installer-module/src/InstallerModuleInstaller.php(34): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/Users/brennon/...', 34, Array)
#1 /Users/brennon/Projects/php/pyrocms.dev/core/anomaly/installer-module/src/Form/InstallerFormHandler.php(28): Anomaly\InstallerModule\InstallerModuleInstaller->install(Array)
#2 [internal function]: Anomaly\InstallerModule\Form\InstallerFormHandler->handle(Object(Anomaly\InstallerModule\Form\InstallerFormBuilder), Object(Anomaly\InstallerModule\InstallerModuleInstaller))
#3 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(502): call_user_func_array(Array, Array)
#4 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(599): Illuminate\Container\Container->call(Array, Array)
#5 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(497): Illuminate\Container\Container->callClass('Anomaly\\Install...', Array, NULL)
#6 /Users/brennon/Projects/php/pyrocms.dev/vendor/anomaly/streams-platform/src/Support/Resolver.php(50): Illuminate\Container\Container->call('Anomaly\\Install...', Array)
#7 /Users/brennon/Projects/php/pyrocms.dev/vendor/anomaly/streams-platform/src/Support/Resolver.php(55): Anomaly\Streams\Platform\Support\Resolver->resolve('Anomaly\\Install...', Array, 'handle')
#8 /Users/brennon/Projects/php/pyrocms.dev/vendor/anomaly/streams-platform/src/Ui/Form/Command/SetFormOptions.php(37): Anomaly\Streams\Platform\Support\Resolver->resolve(Array, Array)
#9 [internal function]: Anomaly\Streams\Platform\Ui\Form\Command\SetFormOptions->handle(Object(Anomaly\Streams\Platform\Support\Resolver), Object(Anomaly\Streams\Platform\Support\Evaluator))
#10 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(502): call_user_func_array(Array, Array)
#11 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(193): Illuminate\Container\Container->call(Array)
#12 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Anomaly\Streams\Platform\Ui\Form\Command\SetFormOptions))
#13 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Anomaly\Streams\Platform\Ui\Form\Command\SetFormOptions))
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Anomaly\Streams\Platform\Ui\Form\Command\SetFormOptions))
#15 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Anomaly\Streams\Platform\Ui\Form\Command\SetFormOptions))
#16 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(205): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(178): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Ui\Form\Command\SetFormOptions), NULL)
#18 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Ui\Form\Command\SetFormOptions))
#19 /Users/brennon/Projects/php/pyrocms.dev/vendor/anomaly/streams-platform/src/Ui/Form/Command/BuildForm.php(56): Anomaly\Streams\Platform\Ui\Form\Command\BuildForm->dispatch(Object(Anomaly\Streams\Platform\Ui\Form\Command\SetFormOptions))
#20 [internal function]: Anomaly\Streams\Platform\Ui\Form\Command\BuildForm->handle()
#21 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Container/Container.php(502): call_user_func_array(Array, Array)
#22 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(193): Illuminate\Container\Container->call(Array)
#23 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Anomaly\Streams\Platform\Ui\Form\Command\BuildForm))
#24 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Anomaly\Streams\Platform\Ui\Form\Command\BuildForm))
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Anomaly\Streams\Platform\Ui\Form\Command\BuildForm))
#26 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Anomaly\Streams\Platform\Ui\Form\Command\BuildForm))
#27 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(205): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(178): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Ui\Form\Command\BuildForm), NULL)
#29 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Ui\Form\Command\BuildForm))
#30 /Users/brennon/Projects/php/pyrocms.dev/vendor/anomaly/streams-platform/src/Ui/Form/FormBuilder.php(177): Anomaly\Streams\Platform\Ui\Form\FormBuilder->dispatch(Object(Anomaly\Streams\Platform\Ui\Form\Command\BuildForm))
#31 /Users/brennon/Projects/php/pyrocms.dev/vendor/anomaly/streams-platform/src/Ui/Form/FormBuilder.php(190): Anomaly\Streams\Platform\Ui\Form\FormBuilder->build(NULL)
#32 /Users/brennon/Projects/php/pyrocms.dev/vendor/anomaly/streams-platform/src/Ui/Form/FormBuilder.php(243): Anomaly\Streams\Platform\Ui\Form\FormBuilder->make(NULL)
#33 /Users/brennon/Projects/php/pyrocms.dev/core/anomaly/installer-module/src/Http/Controller/InstallerController.php(35): Anomaly\Streams\Platform\Ui\Form\FormBuilder->render()
#34 [internal function]: Anomaly\InstallerModule\Http\Controller\InstallerController->index(Object(Anomaly\InstallerModule\Form\InstallerFormBuilder))
#35 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#36 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('index', Array)
#37 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Anomaly\InstallerModule\Http\Controller\InstallerController), Object(Illuminate\Routing\Route), 'index')
#38 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /Users/brennon/Projects/php/pyrocms.dev/vendor/anomaly/streams-platform/src/Http/Middleware/CheckSiteStatus.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Anomaly\Streams\Platform\Http\Middleware\CheckSiteStatus->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#43 /Users/brennon/Projects/php/pyrocms.dev/vendor/barryvdh/laravel-stack-middleware/src/ClosureHttpKernel.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /Users/brennon/Projects/php/pyrocms.dev/vendor/symfony/http-kernel/HttpCache/HttpCache.php(493): Barryvdh\StackMiddleware\ClosureHttpKernel->handle(Object(Illuminate\Http\Request), 1, true)
#45 /Users/brennon/Projects/php/pyrocms.dev/vendor/symfony/http-kernel/HttpCache/HttpCache.php(450): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Illuminate\Http\Request), true)
#46 /Users/brennon/Projects/php/pyrocms.dev/vendor/symfony/http-kernel/HttpCache/HttpCache.php(350): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Illuminate\Http\Request), true)
#47 /Users/brennon/Projects/php/pyrocms.dev/vendor/symfony/http-kernel/HttpCache/HttpCache.php(214): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Illuminate\Http\Request), true)
#48 /Users/brennon/Projects/php/pyrocms.dev/vendor/barryvdh/laravel-stack-middleware/src/ClosureMiddleware.php(37): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Illuminate\Http\Request))
#49 [internal function]: Barryvdh\StackMiddleware\ClosureMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#51 /Users/brennon/Projects/php/pyrocms.dev/vendor/anomaly/streams-platform/src/Http/Middleware/ForceHttps.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Anomaly\Streams\Platform\Http\Middleware\ForceHttps->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#54 /Users/brennon/Projects/php/pyrocms.dev/vendor/anomaly/streams-platform/src/Http/Middleware/ApplicationReady.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 [internal function]: Anomaly\Streams\Platform\Http\Middleware\ApplicationReady->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#57 /Users/brennon/Projects/php/pyrocms.dev/vendor/anomaly/streams-platform/src/Http/Middleware/VerifyCsrfToken.php(69): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 [internal function]: Anomaly\Streams\Platform\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#60 /Users/brennon/Projects/php/pyrocms.dev/vendor/anomaly/streams-platform/src/Http/Middleware/CheckForMaintenanceMode.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 [internal function]: Anomaly\Streams\Platform\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#63 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#65 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#66 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Anomaly\InstallerModule\Http\Controller\InstallerController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#67 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(201): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Anomaly\\Install...', 'index')
#68 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#69 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(704): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#70 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#71 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#72 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#74 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(706): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#75 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(671): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#76 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Routing/Router.php(631): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#77 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#78 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#79 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#80 /Users/brennon/Projects/php/pyrocms.dev/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#82 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#83 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(54): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#85 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#86 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#87 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#88 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#89 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#90 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#91 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#92 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#93 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#94 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#95 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#96 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#97 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#98 /Users/brennon/Projects/php/pyrocms.dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#99 /Users/brennon/Projects/php/pyrocms.dev/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#100 {main} 
```

**Comment by ptrckvzn** [comment]
I get the same error in the javascript console. The installation stops after a few seconds.
I am using pyrocms-3.0-beta1 and Homestead in the pyrocms folder.

<img width="1437" alt="capture d ecran 2015-10-29 a 22 11 25" src="https://cloud.githubusercontent.com/assets/6365432/10836925/0dbacfd2-7e8a-11e5-82e7-2d2b3cbaccfe.png">

**Comment by RyanThompson** [comment]
@bloveless can you try this again? I would think that package would have updated. If it persists.. maybe jQuery isn't being pulled in correctly?

**Comment by bloveless** [comment]
@RyanThompson I get the same issue when I try to install from and existing .env where APP_DEBUG=true

I can install just fine if I delete .env and type all the information again.

**Comment by bloveless** [comment]
Though I don't get the message in the error log. I think the installer just has issues when phpdebugbar is included.

**Comment by ptrckvzn** [comment]
If that's of any help, I was able to install just fine by setting APP_DEBUG to false.

**Comment by bloveless** [comment]
Thanks for the tip. I am able to install with APP_DEBUG set to false as well.

**Comment by themccallister** [comment]
I just tried to install the latest beta with Homestead and PHP 7. Getting the same error..

https://www.dropbox.com/s/atiky761fqrl34g/Screenshot%202016-01-26%2017.31.06.png?dl=0

**Comment by RyanThompson** [comment]
Try again but disable debugging. It breaks JS for some reason.

.env -> APP_DEBUG=false


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by themccallister** [comment]
Thanks @RyanThompson, I did try that before posting - still no luck. Cleared logs/storage/permissions and everything. Even a reinstall with composer, no luck.

**Comment by RyanThompson** [comment]
It gives you the same JS error? jQuery not being found basically. 

If debugging is disabled then the debug bar won't display and you will see the progress bar. 

If the progress bar is failing then you will need to open your web inspector's network activity monitor and watch for the 500 from one of the steps. 

But, the image you sent is JS related and very consistent with debug bar being enabled. Note, though, that it does not display. 


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by themccallister** [comment]
Hmm, to be clear. Enabled debug does not show the PHPDebugbar...

**Comment by RyanThompson** [comment]
Correct, but it DOES try (and results in JS issues in the installer). So make sure that is disabled and try again.

You can also use the CLI installer `php artisan install:streams`

**Comment by mysequel** [comment]
I had same experience when install pyrocms3 on Homestead, got stuck on installation page, and after check browser console, got same warning as above.

I tried to check .env and APP_DEBUG=false already, but still got stuck of installation process

then i tried your solution to use CLI installer, and it's working properly

**Comment by RyanThompson** [comment]
Ima go ahead and close this bad boy out and say don't install with debug enabled. It's hard to do unless you're really tying now. And the rabbit hole is deep
