### ISSUE TITLE
Installation on Windows fails

### ISSUE THREAD

**Issue by Remo** [pyrocms/pyrocms#3558]
I've been trying to get PyroCMS working, but since my vagrant box is having issues with Windows 10 I tried to run it directly on Windows. So far without much success:

I ran this and then started the webserver:
`composer create-project pyrocms/pyrocms=3.0-beta1 --prefer-source`

After entering all information some progress was made, but eventually I've received an error 500. Log shows me this:
```
[2015-11-14 18:57:05] local.ERROR: exception 'ErrorException' with message 'mkdir(): Invalid argument' in C:\work\pyrocms\vendor\league\flysystem\src\Adapter\Local.php:345
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mkdir(): Invali...', 'C:\\work\\pyrocms...', 345, Array)
#1 C:\work\pyrocms\vendor\league\flysystem\src\Adapter\Local.php(345): mkdir('C:\\work\\pyrocms...', 493, true)
#2 C:\work\pyrocms\vendor\league\flysystem\src\Filesystem.php(259): League\Flysystem\Adapter\Local->createDir('C:\\work\\pyrocms...', Object(League\Flysystem\Config))
#3 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemAdapter.php(272): League\Flysystem\Filesystem->createDir('C:\\work\\pyrocms...')
#4 C:\work\pyrocms\core\anomaly\search-module\src\SearchModule.php(51): Illuminate\Filesystem\FilesystemAdapter->makeDirectory('C:\\work\\pyrocms...', 511, true, true)
#5 [internal function]: Anomaly\SearchModule\SearchModule->onInstalled(Object(Illuminate\Filesystem\FilesystemAdapter), Object(Anomaly\Streams\Platform\Application\Application))
#6 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Container\Container.php(502): call_user_func_array(Array, Array)
#7 C:\work\pyrocms\vendor\anomaly\streams-platform\src\Traits\FiresCallbacks.php(53): Illuminate\Container\Container->call(Array, Array)
#8 C:\work\pyrocms\vendor\anomaly\streams-platform\src\Addon\Module\Console\Install.php(49): Anomaly\Streams\Platform\Addon\Addon->fire('installed')
#9 [internal function]: Anomaly\Streams\Platform\Addon\Module\Console\Install->fire(Object(Anomaly\Streams\Platform\Addon\Module\ModuleManager), Object(Anomaly\Streams\Platform\Addon\Module\ModuleCollection))
#10 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Container\Container.php(502): call_user_func_array(Array, Array)
#11 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Console\Command.php(150): Illuminate\Container\Container->call(Array)
#12 C:\work\pyrocms\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#13 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Console\Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#14 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Console\Application.php(62): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#15 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(157): Illuminate\Console\Application->call('module:install', Array)
#16 C:\work\pyrocms\vendor\anomaly\streams-platform\src\Installer\Console\Command\LoadModuleInstallers.php(56): Illuminate\Foundation\Console\Kernel->call('module:install', Array)
#17 [internal function]: Anomaly\Streams\Platform\Installer\Console\Command\LoadModuleInstallers->Anomaly\Streams\Platform\Installer\Console\Command\{closure}(Object(App\Console\Kernel))
#18 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Container\Container.php(502): call_user_func_array(Object(Closure), Array)
#19 C:\work\pyrocms\core\anomaly\installer-module\src\Http\Controller\InstallerController.php(90): Illuminate\Container\Container->call(Object(Closure))
#20 [internal function]: Anomaly\InstallerModule\Http\Controller\InstallerController->run(Object(Illuminate\Foundation\Application), '14')
#21 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(256): call_user_func_array(Array, Array)
#22 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('run', Array)
#23 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Anomaly\InstallerModule\Http\Controller\InstallerController), Object(Illuminate\Routing\Route), 'run')
#24 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 C:\work\pyrocms\vendor\anomaly\streams-platform\src\Http\Middleware\CheckSiteStatus.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 [internal function]: Anomaly\Streams\Platform\Http\Middleware\CheckSiteStatus->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#29 C:\work\pyrocms\vendor\barryvdh\laravel-stack-middleware\src\ClosureHttpKernel.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 C:\work\pyrocms\vendor\symfony\http-kernel\HttpCache\HttpCache.php(487): Barryvdh\StackMiddleware\ClosureHttpKernel->handle(Object(Illuminate\Http\Request), 1, true)
#31 C:\work\pyrocms\vendor\symfony\http-kernel\HttpCache\HttpCache.php(444): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Illuminate\Http\Request), true)
#32 C:\work\pyrocms\vendor\symfony\http-kernel\HttpCache\HttpCache.php(344): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Illuminate\Http\Request), true)
#33 C:\work\pyrocms\vendor\symfony\http-kernel\HttpCache\HttpCache.php(210): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Illuminate\Http\Request), true)
#34 C:\work\pyrocms\vendor\barryvdh\laravel-stack-middleware\src\ClosureMiddleware.php(37): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Illuminate\Http\Request))
#35 [internal function]: Barryvdh\StackMiddleware\ClosureMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#37 C:\work\pyrocms\vendor\anomaly\streams-platform\src\Http\Middleware\ForceHttps.php(61): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Anomaly\Streams\Platform\Http\Middleware\ForceHttps->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#40 C:\work\pyrocms\vendor\anomaly\streams-platform\src\Http\Middleware\ApplicationReady.php(58): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Anomaly\Streams\Platform\Http\Middleware\ApplicationReady->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#43 C:\work\pyrocms\vendor\anomaly\streams-platform\src\Http\Middleware\VerifyCsrfToken.php(69): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Anomaly\Streams\Platform\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#46 C:\work\pyrocms\vendor\anomaly\streams-platform\src\Http\Middleware\CheckForMaintenanceMode.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Anomaly\Streams\Platform\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#49 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Anomaly\InstallerModule\Http\Controller\InstallerController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'run')
#53 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Route.php(201): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Anomaly\\Install...', 'run')
#54 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#55 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Router.php(704): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#58 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#60 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Router.php(706): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#61 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Router.php(671): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#62 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Routing\Router.php(631): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#63 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#64 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#65 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#66 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(54): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#69 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#72 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#74 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#75 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#76 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#77 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#78 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#79 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#80 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#81 C:\work\pyrocms\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#82 C:\work\pyrocms\public\index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#83 {main}  
```

The problem seems to happen in this line:
https://github.com/anomalylabs/search-module/blob/master/src/SearchModule.php#L51

`getStoragePath` returns a full path, but when flysystem is called, it also adds a path, see `applyPathPrefix`:

```php
public function createDir($dirname, Config $config)
{
    $location = $this->applyPathPrefix($dirname);
    $umask = umask(0);
    $visibility = $config->get('visibility', 'public');

    if (! is_dir($location) && !mkdir($location, $this->permissionMap['dir'][$visibility], true)) {
        $return = false;
    } else {
        $return = ['path' => $dirname, 'type' => 'dir'];
    }

    umask($umask);

    return $return;
}
```

The path it tries to create looks like this: `C:\work\pyrocms\storage\app\C:\work\pyrocms\storage\streams\default\search\zend`. That of course doesn't work..

Never looked at PyroCMS before, not sure what the best way is to fix this and also not sure if this is Windows only..

**Comment by Remo** [comment]
cli installer has the same issue:

```
1/26 Running core migrations.
2/26 Running application migrations.
3/26 Running other migrations.
4/26 Installing: Addons Module
5/26 Installing: Appearance Module
6/26 Installing: Configuration Module
7/26 Installing: Dashboard Module
8/26 Installing: Files Module
9/26 Installing: Navigation Module
10/26 Installing: Pages Module
11/26 Installing: Partials Module
12/26 Installing: Posts Module
13/26 Installing: Preferences Module
14/26 Installing: Redirects Module
15/26 Installing: Search Module



  [ErrorException]
  mkdir(): Invalid argument
```

**Comment by edster** [comment]
Windows only, I ran into the same issues.

**Comment by RyanThompson** [comment]
Can you try this again - path issues have been resolved in Beta2

**Comment by Remo** [comment]
installation works, thanks!

**Comment by RyanThompson** [comment]
Excellent!

**Comment by azazqadir** [comment]
Something similar is happening to me. I am not sure where to report it, so doing it here. I was able to successfully install Pyro on LEMP based stack. However, when I am trying to install and configure it on my [php web hosting](https://www.cloudways.com/en/php-cloud-hosting.php), I am getting 500 server error. I have no clue what I am doing wrong here.
