### ISSUE TITLE
Using artisan's app:name task give errors (PSR-4)

### ISSUE THREAD

**Issue by PMK** [pyrocms/pyrocms#3810]
I create a new project with PyroCMS. Then I use the Artisan command to change my project's App name. Laravel supports PSR-4, but this action triggers some errors. At the end I would like to implement the CMS on an existing Laravel 5.1 LTS site, with using an App name.

```
$ composer create-project pyrocms/pyrocms
[...] Everything went well, no errors

$ php artisan app:name Testname
PHP Fatal error:  Class 'App\Exceptions\Handler' not found in pyrocms/vendor/anomaly/streams-platform/src/Exception/ExceptionHandler.php on line 19
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class Anomaly\Streams\Platform\Exception\ExceptionHandler does not exist' in pyrocms/bootstrap/cache/compiled.php:1291
Stack trace:
#0 pyrocms/bootstrap/cache/compiled.php(1291): ReflectionClass->__construct('Anomaly\\Streams...')
#1 pyrocms/bootstrap/cache/compiled.php(1242): Illuminate\Container\Container->build('Anomaly\\Streams...', Array)
#2 pyrocms/bootstrap/cache/compiled.php(1783): Illuminate\Container\Container->make('Anomaly\\Streams...', Array)
#3 pyrocms/bootstrap/cache/compiled.php(1065): Illuminate\Foundation\Application->make('Anomaly\\Streams...', Array)
#4 pyrocms/bootstrap/cache/compiled.php(1289): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illum in pyrocms/bootstrap/cache/compiled.php on line 1291
```

In an existing Laravel 5.1 LTS site, using already an App name, the same is happening.

```
PHP Fatal error:  Class 'App\Exceptions\Handler' not found in /home/vagrant/l51/vendor/anomaly/streams-platform/src/Exception/ExceptionHandler.php on line 18
PHP Stack trace:
PHP   1. {main}() /home/vagrant/l51/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/vagrant/l51/artisan:35
PHP   3. Illuminate\Foundation\Console\Kernel->reportException() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:109
PHP   4. Illuminate\Container\Container->offsetGet() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:250
PHP   5. Illuminate\Foundation\Application->make() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:1167
PHP   6. Illuminate\Container\Container->make() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:674
PHP   7. Illuminate\Container\Container->build() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:631
PHP   8. Illuminate\Container\Container->Illuminate\Container\{closure}() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
PHP   9. Illuminate\Foundation\Application->make() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:220
PHP  10. Illuminate\Container\Container->make() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:674
PHP  11. Illuminate\Container\Container->build() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:631
PHP  12. ReflectionClass->__construct() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:741
PHP  13. spl_autoload_call() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:741
PHP  14. Composer\Autoload\ClassLoader->loadClass() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:741
PHP  15. Composer\Autoload\includeFile() /home/vagrant/l51/vendor/composer/ClassLoader.php:301
PHP  16. include() /home/vagrant/l51/vendor/composer/ClassLoader.php:412
PHP Fatal error:  Uncaught ReflectionException: Class Anomaly\Streams\Platform\Exception\ExceptionHandler does not exist in /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:741
Stack trace:
#0 /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php(741): ReflectionClass->__construct('Anomaly\\Streams...')
#1 /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Anomaly\\Streams...', Array)
#2 /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Anomaly\\Streams...', Array)
#3 /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php(220): Illuminate\Foundation\Application->make('Anomaly\\Streams...', Array)
#4 /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application) in /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 741
PHP Stack trace:
PHP   1. {main}() /home/vagrant/l51/artisan:0
PHP   2. Illuminate\Foundation\Console\Kernel->handle() /home/vagrant/l51/artisan:35
PHP   3. Illuminate\Foundation\Console\Kernel->reportException() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:109
PHP   4. Illuminate\Container\Container->offsetGet() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:250
PHP   5. Illuminate\Foundation\Application->make() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:1167
PHP   6. Illuminate\Container\Container->make() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:674
PHP   7. Illuminate\Container\Container->build() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:631
PHP   8. Illuminate\Container\Container->Illuminate\Container\{closure}() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:738
PHP   9. Illuminate\Foundation\Application->make() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:220
PHP  10. Illuminate\Container\Container->make() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:674
PHP  11. Illuminate\Container\Container->build() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:631
PHP  12. ReflectionClass->__construct() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:741
PHP  13. spl_autoload_call() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:741
PHP  14. Composer\Autoload\ClassLoader->loadClass() /home/vagrant/l51/vendor/laravel/framework/src/Illuminate/Container/Container.php:741
PHP  15. Composer\Autoload\includeFile() /home/vagrant/l51/vendor/composer/ClassLoader.php:301
PHP  16. include() /home/vagrant/l51/vendor/composer/ClassLoader.php:412
```

I assume that "App" in `App\Exceptions\Handler` cannot be found since the name changed. I'm not sure how to fix this using PSR-4. Maybe PyroCMS needs to use `app_path()`?

Thank you in advance.

**Comment by RyanThompson** [comment]
Hi there! I would approach this a little differently. If I may suggest, try requiring streams-platform then the addons and go from there.

While this should work and I will most definitely look into why it's complaining at you - it may be easier the other way around.

I've honestly never changed an app name so I am not certain what all it changes / does.


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by PMK** [comment]
Hello,
Thank you for your reply.

I think I don't understand you. If I'm following the documentation on your website, and use the existing Laravel functionality, I get this error. If I look in `composer.json`, I see `streams-platform` being used. How should I do it differently?

You can change the project's App name, what is optional. In my case I have changed the name. For more info, check the [Laravel docs](https://laravel.com/docs/5.1/#naming-your-application).

About this issue
When I change the file `anomaly/streams-platform/src/Exception/ExceptionHandler.php`, replacing `App\Exceptions\Handler` with `Illuminate\Foundation\Exceptions\Handler` to continue running the code, I get in a different class a similar error: `Fatal error: Class 'App\Console\Kernel' not found in vendor/anomaly/streams-platform/src/Console/Kernel.php on line 14`.

So, if I update my project's App name, the "App" namespace is not existing anymore. This is updated in the composer.json's `autoload` -> `psr-4` key. PyroCMS plus its dependencies are relaying on the "App" namespace (because in the source it wants to load something from the App namespace) and a vendor package should not relay on the project's source.
With `app()->getNamespace();` you get the configured namespace name, but to use it like you want to, I don't know how to do that.

I will look further into this.

**Comment by RyanThompson** [comment]
Aha, I understand now.. 

I am not entirely sure about this one. Because, like you say, I do auto load classes from the app namespace in order to override them.

My initial thought it is to copy the classes (or whats needed) or even extend the app's child class instead (skip the app version). And where that doesn't work or isn't enough then we can bind to the App class but with the appropriate namespace (in the StreamsServiceProvider).

This is an important bug you've discovered here! Would you be open to doing some of the leg work here to get things started off in the right direction? I would be more than happy to help guide you and finish it up with ya.

**Comment by RyanThompson** [comment]
Fixed! Enjoy app:name freedom ^_^

https://github.com/anomalylabs/streams-platform/commit/8e331c3fbf5eb3089cda4221ef776165a1bb3eb1
