### ISSUE TITLE
No such file or directory core/anomaly/dashboard-module/src/Seeder/WidgetSeeder.php:94

### ISSUE THREAD

**Issue by themccallister** [pyrocms/pyrocms#3811]
Went to install PyroCMS locally and recvied this error message:

(**Note**: this was a fresh install and new Docker container)

```
[2016-08-13 01:07:15] local.ERROR: ErrorException: file_get_contents(/var/www/core/anomaly/xml_feed_widget-extension/resources/stubs/template.stub): failed to open stream: No such file or directory in /var/www/core/anomaly/dashboard-module/src/Seeder/WidgetSeeder.php:94
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_get_conten...', '/var/www/core/a...', 94, Array)
#1 /var/www/core/anomaly/dashboard-module/src/Seeder/WidgetSeeder.php(94): file_get_contents('/var/www/core/a...')
#2 /var/www/vendor/anomaly/streams-platform/src/Database/Seeder/Seeder.php(74): Anomaly\DashboardModule\Seeder\WidgetSeeder->run()
#3 /var/www/core/anomaly/dashboard-module/src/DashboardModuleSeeder.php(24): Anomaly\Streams\Platform\Database\Seeder\Seeder->call('Anomaly\\Dashboa...')
#4 /var/www/vendor/anomaly/streams-platform/src/Database/Seeder/Seeder.php(74): Anomaly\DashboardModule\DashboardModuleSeeder->run()
#5 /var/www/vendor/anomaly/streams-platform/src/Database/Seeder/Command/SeedHandler.php(96): Anomaly\Streams\Platform\Database\Seeder\Seeder->call('Anomaly\\Dashboa...')
#6 /var/www/vendor/anomaly/streams-platform/src/Database/Seeder/Command/SeedHandler.php(76): Anomaly\Streams\Platform\Database\Seeder\Command\SeedHandler->call('Anomaly\\Dashboa...')
#7 [internal function]: Anomaly\Streams\Platform\Database\Seeder\Command\SeedHandler->handle(Object(Anomaly\Streams\Platform\Database\Seeder\Command\Seed))
#8 /var/www/bootstrap/cache/compiled.php(9496): call_user_func(Array, Object(Anomaly\Streams\Platform\Database\Seeder\Command\Seed))
#9 [internal function]: Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Anomaly\Streams\Platform\Database\Seeder\Command\Seed))
#10 /var/www/bootstrap/cache/compiled.php(9642): call_user_func(Object(Closure), Object(Anomaly\Streams\Platform\Database\Seeder\Command\Seed))
#11 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Anomaly\Streams\Platform\Database\Seeder\Command\Seed))
#12 /var/www/bootstrap/cache/compiled.php(9624): call_user_func(Object(Closure), Object(Anomaly\Streams\Platform\Database\Seeder\Command\Seed))
#13 /var/www/bootstrap/cache/compiled.php(9497): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /var/www/bootstrap/cache/compiled.php(9483): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Database\Seeder\Command\Seed), NULL)
#15 /var/www/bootstrap/cache/compiled.php(5444): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Database\Seeder\Command\Seed))
#16 /var/www/vendor/anomaly/streams-platform/src/Database/Seeder/Console/SeedCommand.php(36): Anomaly\Streams\Platform\Database\Seeder\Console\SeedCommand->dispatch(Object(Anomaly\Streams\Platform\Database\Seeder\Command\Seed))
#17 [internal function]: Anomaly\Streams\Platform\Database\Seeder\Console\SeedCommand->fire()
#18 /var/www/bootstrap/cache/compiled.php(1187): call_user_func_array(Array, Array)
#19 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#20 /var/www/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#21 /var/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#22 /var/www/vendor/symfony/console/Application.php(844): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#23 /var/www/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Anomaly\Streams\Platform\Database\Seeder\Console\SeedCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#24 /var/www/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#25 /var/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(64): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\BufferedOutput))
#26 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(159): Illuminate\Console\Application->call('db:seed', Object(Illuminate\Support\Collection))
#27 /var/www/vendor/anomaly/streams-platform/src/Installer/Console/Command/LoadModuleSeeders.php(59): Illuminate\Foundation\Console\Kernel->call('db:seed', Array)
#28 [internal function]: Anomaly\Streams\Platform\Installer\Console\Command\LoadModuleSeeders->Anomaly\Streams\Platform\Installer\Console\Command\{closure}(Object(App\Console\Kernel))
#29 /var/www/bootstrap/cache/compiled.php(1187): call_user_func_array(Object(Closure), Array)
#30 /var/www/core/anomaly/installer-module/src/Http/Controller/InstallerController.php(122): Illuminate\Container\Container->call(Object(Closure))
#31 [internal function]: Anomaly\InstallerModule\Http\Controller\InstallerController->seed(Object(Illuminate\Foundation\Application), Object(Illuminate\Events\Dispatcher), '2')
#32 /var/www/bootstrap/cache/compiled.php(8922): call_user_func_array(Array, Array)
#33 /var/www/bootstrap/cache/compiled.php(8991): Illuminate\Routing\Controller->callAction('seed', Array)
#34 /var/www/bootstrap/cache/compiled.php(8971): Illuminate\Routing\ControllerDispatcher->call(Object(Anomaly\InstallerModule\Http\Controller\InstallerController), Object(Illuminate\Routing\Route), 'seed')
#35 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/bootstrap/cache/compiled.php(9642): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 /var/www/vendor/anomaly/streams-platform/src/Http/Middleware/CheckForMaintenanceMode.php(77): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Anomaly\Streams\Platform\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#40 /var/www/vendor/barryvdh/laravel-stack-middleware/src/ClosureHttpKernel.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/vendor/symfony/http-kernel/HttpCache/HttpCache.php(487): Barryvdh\StackMiddleware\ClosureHttpKernel->handle(Object(Illuminate\Http\Request), 1, true)
#42 /var/www/vendor/symfony/http-kernel/HttpCache/HttpCache.php(444): Symfony\Component\HttpKernel\HttpCache\HttpCache->forward(Object(Illuminate\Http\Request), true)
#43 /var/www/vendor/symfony/http-kernel/HttpCache/HttpCache.php(344): Symfony\Component\HttpKernel\HttpCache\HttpCache->fetch(Object(Illuminate\Http\Request), true)
#44 /var/www/vendor/symfony/http-kernel/HttpCache/HttpCache.php(210): Symfony\Component\HttpKernel\HttpCache\HttpCache->lookup(Object(Illuminate\Http\Request), true)
#45 /var/www/vendor/barryvdh/laravel-stack-middleware/src/ClosureMiddleware.php(36): Symfony\Component\HttpKernel\HttpCache\HttpCache->handle(Object(Illuminate\Http\Request))
#46 [internal function]: Barryvdh\StackMiddleware\ClosureMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /var/www/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#48 /var/www/vendor/anomaly/streams-platform/src/Http/Middleware/PoweredBy.php(46): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Anomaly\Streams\Platform\Http\Middleware\PoweredBy->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /var/www/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#51 /var/www/vendor/anomaly/streams-platform/src/Http/Middleware/SetLocale.php(92): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Anomaly\Streams\Platform\Http\Middleware\SetLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /var/www/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#54 /var/www/vendor/anomaly/streams-platform/src/Http/Middleware/ApplicationReady.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 [internal function]: Anomaly\Streams\Platform\Http\Middleware\ApplicationReady->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /var/www/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#57 /var/www/vendor/anomaly/streams-platform/src/Http/Middleware/VerifyCsrfToken.php(69): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 [internal function]: Anomaly\Streams\Platform\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /var/www/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#60 /var/www/core/anomaly/users-module/src/Http/Middleware/AuthorizeRoutePermission.php(102): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 [internal function]: Anomaly\UsersModule\Http\Middleware\AuthorizeRoutePermission->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /var/www/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#63 /var/www/core/anomaly/users-module/src/Http/Middleware/AuthorizeControlPanel.php(45): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 [internal function]: Anomaly\UsersModule\Http\Middleware\AuthorizeControlPanel->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /var/www/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#66 /var/www/core/anomaly/users-module/src/Http/Middleware/AuthorizeModuleAccess.php(55): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 [internal function]: Anomaly\UsersModule\Http\Middleware\AuthorizeModuleAccess->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /var/www/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#69 /var/www/core/anomaly/users-module/src/Http/Middleware/AuthorizeRouteRoles.php(99): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 [internal function]: Anomaly\UsersModule\Http\Middleware\AuthorizeRouteRoles->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 /var/www/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#72 /var/www/core/anomaly/users-module/src/Http/Middleware/CheckSecurity.php(87): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 [internal function]: Anomaly\UsersModule\Http\Middleware\CheckSecurity->handle(Object(Illuminate\Http\Request), Object(Closure))
#74 /var/www/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#75 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#76 /var/www/bootstrap/cache/compiled.php(9624): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#77 /var/www/bootstrap/cache/compiled.php(8972): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#78 /var/www/bootstrap/cache/compiled.php(8957): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Anomaly\InstallerModule\Http\Controller\InstallerController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'seed')
#79 /var/www/bootstrap/cache/compiled.php(7906): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Anomaly\\Install...', 'seed')
#80 /var/www/bootstrap/cache/compiled.php(7877): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#81 /var/www/bootstrap/cache/compiled.php(7530): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#82 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#83 /var/www/bootstrap/cache/compiled.php(9642): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#84 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#85 /var/www/bootstrap/cache/compiled.php(9624): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#86 /var/www/bootstrap/cache/compiled.php(7531): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#87 /var/www/bootstrap/cache/compiled.php(7519): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#88 /var/www/bootstrap/cache/compiled.php(7504): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#89 /var/www/bootstrap/cache/compiled.php(2310): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#90 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#91 /var/www/bootstrap/cache/compiled.php(9642): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#92 /var/www/bootstrap/cache/compiled.php(12993): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#93 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#94 /var/www/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#95 /var/www/bootstrap/cache/compiled.php(11585): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#96 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#97 /var/www/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#98 /var/www/bootstrap/cache/compiled.php(12730): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#99 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#100 /var/www/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#101 /var/www/bootstrap/cache/compiled.php(12667): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#102 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#103 /var/www/bootstrap/cache/compiled.php(9634): call_user_func_array(Array, Array)
#104 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#105 /var/www/bootstrap/cache/compiled.php(9624): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#106 /var/www/bootstrap/cache/compiled.php(2257): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#107 /var/www/bootstrap/cache/compiled.php(2240): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#108 /var/www/public/index.php(56): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#109 {main}  
[2016-08-13 01:07:15] local.ERROR: Twig_Error_Loader: Template "theme::errors/500" is not defined (). in /var/www/vendor/twig/twig/lib/Twig/Loader/Chain.php:115
Stack trace:
#0 /var/www/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Chain->getCacheKey('theme::errors/5...')
#1 /var/www/vendor/twig/twig/lib/Twig/Environment.php(324): Twig_Environment->getTemplateClass('theme::errors/5...', NULL)
#2 /var/www/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig_Environment->loadTemplate('theme::errors/5...', NULL)
#3 /var/www/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\Bridge->loadTemplate('theme::errors/5...')
#4 /var/www/vendor/rcrowe/twigbridge/src/Engine/Twig.php(90): TwigBridge\Engine\Compiler->load('theme::errors/5...')
#5 /var/www/bootstrap/cache/compiled.php(14638): TwigBridge\Engine\Twig->get('theme::errors/5...', Array)
#6 /var/www/bootstrap/cache/compiled.php(14626): Illuminate\View\View->getContents()
#7 /var/www/bootstrap/cache/compiled.php(14610): Illuminate\View\View->renderContents()
#8 /var/www/bootstrap/cache/compiled.php(15770): Illuminate\View\View->render()
#9 /var/www/bootstrap/cache/compiled.php(15287): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#10 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 500, Array)
#11 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(71): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 500, Array)
#12 /var/www/vendor/anomaly/streams-platform/src/Exception/ExceptionHandler.php(42): Illuminate\Routing\ResponseFactory->view('streams::errors...', Array, 500)
#13 /var/www/bootstrap/cache/compiled.php(2327): Anomaly\Streams\Platform\Exception\ExceptionHandler->render(Object(Illuminate\Http\Request), Object(ErrorException))
#14 /var/www/bootstrap/cache/compiled.php(2243): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(ErrorException))
#15 /var/www/public/index.php(56): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#16 {main}

Next InvalidArgumentException: Error loading theme::errors/500: Template "theme::errors/500" is not defined (). in /var/www/vendor/rcrowe/twigbridge/src/Engine/Compiler.php:101
Stack trace:
#0 /var/www/vendor/rcrowe/twigbridge/src/Engine/Twig.php(90): TwigBridge\Engine\Compiler->load('theme::errors/5...')
#1 /var/www/bootstrap/cache/compiled.php(14638): TwigBridge\Engine\Twig->get('theme::errors/5...', Array)
#2 /var/www/bootstrap/cache/compiled.php(14626): Illuminate\View\View->getContents()
#3 /var/www/bootstrap/cache/compiled.php(14610): Illuminate\View\View->renderContents()
#4 /var/www/bootstrap/cache/compiled.php(15770): Illuminate\View\View->render()
#5 /var/www/bootstrap/cache/compiled.php(15287): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#6 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 500, Array)
#7 /var/www/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(71): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 500, Array)
#8 /var/www/vendor/anomaly/streams-platform/src/Exception/ExceptionHandler.php(42): Illuminate\Routing\ResponseFactory->view('streams::errors...', Array, 500)
#9 /var/www/bootstrap/cache/compiled.php(2327): Anomaly\Streams\Platform\Exception\ExceptionHandler->render(Object(Illuminate\Http\Request), Object(ErrorException))
#10 /var/www/bootstrap/cache/compiled.php(2243): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(ErrorException))
#11 /var/www/public/index.php(56): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#12 {main}  
[2016-08-13 01:07:15] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught Twig_Error_Loader: Template "theme::errors/500" is not defined (). in /var/www/vendor/twig/twig/lib/Twig/Loader/Chain.php:115
Stack trace:
#0 /var/www/vendor/twig/twig/lib/Twig/Environment.php(266): Twig_Loader_Chain->getCacheKey('theme::errors/5...')
#1 /var/www/vendor/twig/twig/lib/Twig/Environment.php(324): Twig_Environment->getTemplateClass('theme::errors/5...', NULL)
#2 /var/www/vendor/rcrowe/twigbridge/src/Bridge.php(75): Twig_Environment->loadTemplate('theme::errors/5...', NULL)
#3 /var/www/vendor/rcrowe/twigbridge/src/Engine/Compiler.php(99): TwigBridge\Bridge->loadTemplate('theme::errors/5...')
#4 /var/www/vendor/rcrowe/twigbridge/src/Engine/Twig.php(90): TwigBridge\Engine\Compiler->load('theme::errors/5...')
#5 /var/www/bootstrap/cache/compiled.php(14638): TwigBridge\Engine\Twig->get('theme::errors/5...', Array)
#6 /var/www/bootstrap/cache/compiled.php(14626): Illuminate\View\View->getContents()
#7 /var/www/bootstrap/cache/compiled.php(14610): Illuminate\View\View->renderContents()
#8 /var/ in /var/www/vendor/rcrowe/twigbridge/src/Engine/Compiler.php:101
Stack trace:
#0 {main}  

```

**Comment by RyanThompson** [comment]
A composer update will fix this - my bad.. I was an air head :-O
