### ISSUE TITLE
Files module: uploading multiple files, some fails with database error

### ISSUE THREAD

**Issue by kimse1** [pyrocms/pyrocms#3866]
I uploaded multiple files, and some of the failed with a 500, but the failed files was uploaded and added to the folder.

```
[2016-09-27 23:22:22] local.ERROR: PDOException: SQLSTATE[HY000]: General error: 5 database is locked in /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php:380
Stack trace:
#0 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php(380): PDOStatement->execute()
#1 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php(337): TeamTNT\TNTSearch\Indexer\TNTIndexer->saveWordlist(Object(TeamTNT\TNTSearch\Support\Collection))
#2 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php(266): TeamTNT\TNTSearch\Indexer\TNTIndexer->saveToIndex(Object(TeamTNT\TNTSearch\Support\Collection), 40)
#3 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php(271): TeamTNT\TNTSearch\Indexer\TNTIndexer->processDocument(Object(TeamTNT\TNTSearch\Support\Collection))
#4 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php(279): TeamTNT\TNTSearch\Indexer\TNTIndexer->insert(Array)
#5 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php(45): TeamTNT\TNTSearch\Indexer\TNTIndexer->update(40, Array)
#6 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Support/Collection.php(228): TeamTNT\Scout\Engines\TNTSearchEngine->TeamTNT\Scout\Engines\{closure}(Object(Anomaly\FilesModule\File\FileModel), 0)
#7 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php(49): Illuminate\Support\Collection->each(Object(Closure))
#8 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/scout/src/Searchable.php(52): TeamTNT\Scout\Engines\TNTSearchEngine->update(Object(Illuminate\Database\Eloquent\Collection))
#9 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/scout/src/Searchable.php(35): Anomaly\Streams\Platform\Entry\EntryModel->queueMakeSearchable(Object(Illuminate\Database\Eloquent\Collection))
#10 [internal function]: Illuminate\Database\Eloquent\Collection->Laravel\Scout\{closure}()
#11 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php(78): call_user_func_array(Object(Closure), Array)
#12 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/scout/src/Searchable.php(98): Illuminate\Support\Collection->__call('searchable', Array)
#13 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/scout/src/ModelObserver.php(76): Anomaly\Streams\Platform\Entry\EntryModel->searchable()
#14 [internal function]: Laravel\Scout\ModelObserver->updated(Object(Anomaly\FilesModule\File\FileModel))
#15 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(348): call_user_func_array(Array, Array)
#16 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(Anomaly\FilesModule\File\FileModel))
#17 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#18 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1665): Illuminate\Events\Dispatcher->fire('eloquent.update...', Array)
#19 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1545): Illuminate\Database\Eloquent\Model->fireModelEvent('eloquent.update...', false)
#20 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/anomaly/streams-platform/src/Model/EloquentModel.php(491): Illuminate\Database\Eloquent\Model->performUpdate(Object(Anomaly\Streams\Platform\Entry\EntryQueryBuilder), Array)
#21 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/anomaly/streams-platform/src/Model/EloquentModel.php(436): Anomaly\Streams\Platform\Model\EloquentModel->saveModel(Array)
#22 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/anomaly/streams-platform/src/Model/EloquentRepository.php(166): Anomaly\Streams\Platform\Model\EloquentModel->save()
#23 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/core/anomaly/files-module/src/File/FileUploader.php(121): Anomaly\Streams\Platform\Model\EloquentRepository->save(Object(Anomaly\FilesModule\File\FileModel))
#24 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/core/anomaly/file-field_type/src/Http/Controller/UploadController.php(50): Anomaly\FilesModule\File\FileUploader->upload(Object(Illuminate\Http\UploadedFile), Object(Anomaly\FilesModule\Folder\FolderModel))
#25 [internal function]: Anomaly\FileFieldType\Http\Controller\UploadController->upload(Object(Anomaly\FilesModule\File\FileUploader), Object(Anomaly\FilesModule\Folder\FolderRepository))
#26 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#27 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('upload', Array)
#28 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Anomaly\FileFieldType\Http\Controller\UploadController), 'upload')
#29 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#30 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(642): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#31 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/PoweredBy.php(38): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\Streams\Platform\Http\Middleware\PoweredBy->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/SetLocale.php(88): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\Streams\Platform\Http\Middleware\SetLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/anomaly/streams-platform/src/Http/Middleware/ApplicationReady.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\Streams\Platform\Http\Middleware\ApplicationReady->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/core/anomaly/users-module/src/Http/Middleware/AuthorizeRoutePermission.php(106): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeRoutePermission->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/core/anomaly/users-module/src/Http/Middleware/AuthorizeControlPanel.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeControlPanel->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/core/anomaly/users-module/src/Http/Middleware/AuthorizeModuleAccess.php(54): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeModuleAccess->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/core/anomaly/users-module/src/Http/Middleware/AuthorizeRouteRoles.php(98): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeRouteRoles->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/core/anomaly/users-module/src/Http/Middleware/CheckSecurity.php(86): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\CheckSecurity->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/core/anomaly/users-module/src/Http/Middleware/Authenticate.php(92): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(644): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#64 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(618): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#65 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Router.php(596): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#66 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(267): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#67 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#68 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#75 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#78 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#80 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#81 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(149): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#82 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#83 /home/kimse/NetBeansProjects/sommercoaching-pyrocms/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#84 {main}  
```

**Comment by RyanThompson** [comment]
You can try reducing the number of concurrent files.. but this is why: http://stackoverflow.com/questions/27902831/sqlite3-sqlstatehy000-general-error-5-database-is-locked

Too much activity. Being that that is an external package not sure what the best approach here is. JS timeout maybe?

**Comment by kimse1** [comment]
Something like this maybe: http://stackoverflow.com/questions/880303/difficulty-running-concurrent-inserts-on-sqlite-database-in-c-sharp/880310#880310

**Comment by RyanThompson** [comment]
I think there might be an issue with search indexing too where it's compounding a bit. I have to look into this more.

**Comment by RyanThompson** [comment]
Unfortunately I am going to close this one without resolve. There are many variables even hardware performance. If you consistently run into this perhaps try reducing the number of allowed parallel uploads in settings -> modules -> files module
