### ISSUE TITLE
[3.2] BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::getTablePrefix()

### ISSUE THREAD

**Issue by huglester** [pyrocms/pyrocms#4101]
Hello,

after upgrading to 3.2, sometimes on login, I get error below.
it stops somewhere in the forms handler probably, because url is: /forms/handle/?????

but if I go to /admin later - I am logged in.

```code

[2017-02-01 08:56:04] local.ERROR: BadMethodCallException: Call to undefined method Illuminate\Database\Query\Builder::getTablePrefix() in /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2450
Stack trace:
#0 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1473): Illuminate\Database\Query\Builder->__call('getTablePrefix', Array)
#1 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3561): Illuminate\Database\Eloquent\Builder->__call('getTablePrefix', Array)
#2 /home/pinigainew/domains/new.pinigai.lt/vendor/anomaly/streams-platform/src/Model/EloquentModel.php(841): Illuminate\Database\Eloquent\Model->__call('getTablePrefix', Array)
#3 /home/pinigainew/domains/new.pinigai.lt/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php(199): Anomaly\Streams\Platform\Model\EloquentModel->__call('getTablePrefix', Array)
#4 /home/pinigainew/domains/new.pinigai.lt/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php(36): TeamTNT\Scout\Engines\TNTSearchEngine->initIndex(Object(Anomaly\UsersModule\User\UserModel))
#5 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/scout/src/Searchable.php(56): TeamTNT\Scout\Engines\TNTSearchEngine->update(Object(Illuminate\Database\Eloquent\Collection))
#6 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/scout/src/Searchable.php(35): Anomaly\Streams\Platform\Entry\EntryModel->queueMakeSearchable(Object(Illuminate\Database\Eloquent\Collection))
#7 [internal function]: Illuminate\Database\Eloquent\Collection->Laravel\Scout\{closure}()
#8 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Support/Traits/Macroable.php(78): call_user_func_array(Object(Closure), Array)
#9 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/scout/src/Searchable.php(112): Illuminate\Support\Collection->__call('searchable', Array)
#10 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/scout/src/ModelObserver.php(61): Anomaly\Streams\Platform\Entry\EntryModel->searchable()
#11 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/scout/src/ModelObserver.php(72): Laravel\Scout\ModelObserver->created(Object(Anomaly\UsersModule\User\UserModel))
#12 [internal function]: Laravel\Scout\ModelObserver->updated(Object(Anomaly\UsersModule\User\UserModel))
#13 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(354): call_user_func_array(Array, Array)
#14 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(Anomaly\UsersModule\User\UserModel))
#15 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#16 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1667): Illuminate\Events\Dispatcher->fire('eloquent.update...', Array)
#17 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1543): Illuminate\Database\Eloquent\Model->fireModelEvent('eloquent.update...', false)
#18 /home/pinigainew/domains/new.pinigai.lt/vendor/anomaly/streams-platform/src/Model/EloquentModel.php(559): Illuminate\Database\Eloquent\Model->performUpdate(Object(Anomaly\Streams\Platform\Entry\EntryQueryBuilder), Array)
#19 /home/pinigainew/domains/new.pinigai.lt/vendor/anomaly/streams-platform/src/Model/EloquentModel.php(504): Anomaly\Streams\Platform\Model\EloquentModel->saveModel(Array)
#20 /home/pinigainew/domains/new.pinigai.lt/vendor/anomaly/streams-platform/src/Model/EloquentRepository.php(171): Anomaly\Streams\Platform\Model\EloquentModel->save()
#21 /home/pinigainew/domains/new.pinigai.lt/core/anomaly/users-module/src/User/UserRepository.php(125): Anomaly\Streams\Platform\Model\EloquentRepository->save(Object(Anomaly\UsersModule\User\UserModel))
#22 /home/pinigainew/domains/new.pinigai.lt/core/anomaly/users-module/src/User/Listener/TouchLastLogin.php(40): Anomaly\UsersModule\User\UserRepository->touchLastLogin(Object(Anomaly\UsersModule\User\UserModel))
#23 [internal function]: Anomaly\UsersModule\User\Listener\TouchLastLogin->handle(Object(Anomaly\UsersModule\User\Event\UserWasLoggedIn))
#24 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(354): call_user_func_array(Array, Array)
#25 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(Anomaly\UsersModule\User\Event\UserWasLoggedIn))
#26 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#27 /home/pinigainew/domains/new.pinigai.lt/core/anomaly/users-module/src/User/UserAuthenticator.php(126): Illuminate\Events\Dispatcher->fire('Anomaly\\UsersMo...')
#28 /home/pinigainew/domains/new.pinigai.lt/core/anomaly/users-module/src/User/Login/LoginFormHandler.php(53): Anomaly\UsersModule\User\UserAuthenticator->login(Object(Anomaly\UsersModule\User\UserModel), false)
#29 [internal function]: Anomaly\UsersModule\User\Login\LoginFormHandler->handle(Object(Anomaly\UsersModule\User\Login\LoginFormBuilder), Object(Anomaly\UsersModule\User\UserAuthenticator), Object(Anomaly\UsersModule\User\UserSecurity), Object(Illuminate\Routing\Redirector))
#30 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#31 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Container/Container.php(603): Illuminate\Container\Container->call(Array, Array)
#32 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Container/Container.php(503): Illuminate\Container\Container->callClass('Anomaly\\UsersMo...', Array, NULL)
#33 /home/pinigainew/domains/new.pinigai.lt/vendor/anomaly/streams-platform/src/Ui/Form/Command/HandleForm.php(50): Illuminate\Container\Container->call('Anomaly\\UsersMo...', Array)
#34 [internal function]: Anomaly\Streams\Platform\Ui\Form\Command\HandleForm->handle(Object(Illuminate\Foundation\Application))
#35 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#36 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#37 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Anomaly\Streams\Platform\Ui\Form\Command\HandleForm))
#38 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Anomaly\Streams\Platform\Ui\Form\Command\HandleForm))
#39 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#40 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(75): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Ui\Form\Command\HandleForm))
#41 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Ui\Form\Command\HandleForm))
#42 /home/pinigainew/domains/new.pinigai.lt/vendor/anomaly/streams-platform/src/Ui/Form/Command/PostForm.php(60): Anomaly\Streams\Platform\Ui\Form\Command\PostForm->dispatch(Object(Anomaly\Streams\Platform\Ui\Form\Command\HandleForm))
#43 [internal function]: Anomaly\Streams\Platform\Ui\Form\Command\PostForm->handle(Object(Illuminate\Events\Dispatcher))
#44 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Container/Container.php(508): call_user_func_array(Array, Array)
#45 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#46 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Anomaly\Streams\Platform\Ui\Form\Command\PostForm))
#47 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Anomaly\Streams\Platform\Ui\Form\Command\PostForm))
#48 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#49 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(75): Illuminate\Bus\Dispatcher->dispatchNow(Object(Anomaly\Streams\Platform\Ui\Form\Command\PostForm))
#50 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php(17): Illuminate\Bus\Dispatcher->dispatch(Object(Anomaly\Streams\Platform\Ui\Form\Command\PostForm))
#51 /home/pinigainew/domains/new.pinigai.lt/vendor/anomaly/streams-platform/src/Ui/Form/FormBuilder.php(241): Anomaly\Streams\Platform\Ui\Form\FormBuilder->dispatch(Object(Anomaly\Streams\Platform\Ui\Form\Command\PostForm))
#52 /home/pinigainew/domains/new.pinigai.lt/vendor/anomaly/streams-platform/src/Http/Controller/FormController.php(39): Anomaly\Streams\Platform\Ui\Form\FormBuilder->post()
#53 [internal function]: Anomaly\Streams\Platform\Http\Controller\FormController->handle(Object(Illuminate\Cache\Repository), Object(Illuminate\Routing\Redirector), '54025f700558998...')
#54 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#55 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('handle', Array)
#56 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Route.php(189): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Anomaly\Streams\Platform\Http\Controller\FormController), 'handle')
#57 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Route.php(144): Illuminate\Routing\Route->runController()
#58 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(653): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#59 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /home/pinigainew/domains/new.pinigai.lt/vendor/anomaly/streams-platform/src/Http/Middleware/CheckForMaintenanceMode.php(76): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\Streams\Platform\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 /home/pinigainew/domains/new.pinigai.lt/vendor/anomaly/streams-platform/src/Http/Middleware/ApplicationReady.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\Streams\Platform\Http\Middleware\ApplicationReady->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /home/pinigainew/domains/new.pinigai.lt/vendor/anomaly/streams-platform/src/Http/Middleware/SetLocale.php(88): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\Streams\Platform\Http\Middleware\SetLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 /home/pinigainew/domains/new.pinigai.lt/vendor/webas/pyro-extensions/src/Http/Middleware/PoweredBy.php(16): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#70 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Webas\Pyro\Extensions\Http\Middleware\PoweredBy->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#73 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#74 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 /home/pinigainew/domains/new.pinigai.lt/core/anomaly/users-module/src/Http/Middleware/AuthorizeRoutePermission.php(106): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#76 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeRoutePermission->handle(Object(Illuminate\Http\Request), Object(Closure))
#77 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 /home/pinigainew/domains/new.pinigai.lt/core/anomaly/users-module/src/Http/Middleware/AuthorizeControlPanel.php(44): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#79 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeControlPanel->handle(Object(Illuminate\Http\Request), Object(Closure))
#80 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 /home/pinigainew/domains/new.pinigai.lt/core/anomaly/users-module/src/Http/Middleware/AuthorizeModuleAccess.php(54): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#82 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeModuleAccess->handle(Object(Illuminate\Http\Request), Object(Closure))
#83 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 /home/pinigainew/domains/new.pinigai.lt/core/anomaly/users-module/src/Http/Middleware/AuthorizeRouteRoles.php(98): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#85 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\AuthorizeRouteRoles->handle(Object(Illuminate\Http\Request), Object(Closure))
#86 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#87 /home/pinigainew/domains/new.pinigai.lt/core/anomaly/users-module/src/Http/Middleware/CheckSecurity.php(86): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#88 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Anomaly\UsersModule\Http\Middleware\CheckSecurity->handle(Object(Illuminate\Http\Request), Object(Closure))
#89 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#90 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#91 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#92 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(629): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#93 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Router.php(607): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#94 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(268): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#95 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#96 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#97 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#98 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#99 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#100 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#101 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#102 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#103 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#104 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#105 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#106 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(137): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#107 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#108 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#109 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#110 /home/pinigainew/domains/new.pinigai.lt/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#111 /home/pinigainew/domains/new.pinigai.lt/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#112 {main} {"identification":{"id":"5595cf71-33fa-43ce-952a-aa66e38c41e3"}}

**Comment by RyanThompson** [comment]
You wanna try updating TNT Search's scout driver?  https://github.com/teamtnt/laravel-scout-tntsearch-driver

**Comment by RyanThompson** [comment]
Pretty sure that's the issue here

**Comment by huglester** [comment]
You mean to 2.x version? Is it what you want me to try?

since streams depends on version 1.1.x

**Comment by RyanThompson** [comment]
I recently updated scout - this should be resolved.
