### ISSUE TITLE
[comments-module] v1.0.6 issues

### ISSUE THREAD

**Issue by Youhan** [pyrocms/pyrocms#4682]
Thank you for the great work on the comments module Ryan.
I was just playing with the module with Pyro being v4.3
First I added it to `composer.json` using `"anomaly/comments-module": "~1.0.0",`
Then I installed the module and made some comments on a post both with a authenticated user ( admin ) and a guest commenter.

#### Problems: 
When I click on `view` I get a 500 error at `admin/comments/view/3`
```
...removed because was redundant...
```

#### When I click on `Edit` I get a 500 error at `admin/comments/edit/2`
```
[2017-11-01 15:36:51] local.ERROR: Call to a member function getId() on null {"userId":1,"email":"admin@admin.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function getId() on null at /Users/me/dev/pyro/core/anomaly/comments-module/src/Comment/Form/CommentFormBuilder.php:174)
[stacktrace]
#0 /Users/me/dev/pyro/vendor/anomaly/streams-platform/src/Ui/Form/Command/SetDefaultParameters.php(98): Anomaly\\CommentsModule\\Comment\\Form\\CommentFormBuilder->getSubjectId()
#1 [internal function]: Anomaly\\Streams\\Platform\\Ui\\Form\\Command\\SetDefaultParameters->handle()
#2 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#3 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#5 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#6 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#7 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Anomaly\\Streams\\Platform\\Ui\\Form\\Command\\SetDefaultParameters))
#8 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Anomaly\\Streams\\Platform\\Ui\\Form\\Command\\SetDefaultParameters))
#9 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#10 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(75): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Anomaly\\Streams\\Platform\\Ui\\Form\\Command\\SetDefaultParameters))
#11 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php(17): Illuminate\\Bus\\Dispatcher->dispatch(Object(Anomaly\\Streams\\Platform\\Ui\\Form\\Command\\SetDefaultParameters))
#12 /Users/me/dev/pyro/vendor/anomaly/streams-platform/src/Ui/Form/Command/BuildForm.php(59): Anomaly\\Streams\\Platform\\Ui\\Form\\Command\\BuildForm->dispatch(Object(Anomaly\\Streams\\Platform\\Ui\\Form\\Command\\SetDefaultParameters))
#13 [internal function]: Anomaly\\Streams\\Platform\\Ui\\Form\\Command\\BuildForm->handle(Object(Illuminate\\Events\\Dispatcher))
#14 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#15 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#16 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#17 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#18 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#19 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Anomaly\\Streams\\Platform\\Ui\\Form\\Command\\BuildForm))
#20 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Anomaly\\Streams\\Platform\\Ui\\Form\\Command\\BuildForm))
#21 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#22 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(75): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Anomaly\\Streams\\Platform\\Ui\\Form\\Command\\BuildForm))
#23 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Bus/DispatchesJobs.php(17): Illuminate\\Bus\\Dispatcher->dispatch(Object(Anomaly\\Streams\\Platform\\Ui\\Form\\Command\\BuildForm))
#24 /Users/me/dev/pyro/vendor/anomaly/streams-platform/src/Ui/Form/FormBuilder.php(187): Anomaly\\Streams\\Platform\\Ui\\Form\\FormBuilder->dispatch(Object(Anomaly\\Streams\\Platform\\Ui\\Form\\Command\\BuildForm))
#25 /Users/me/dev/pyro/vendor/anomaly/streams-platform/src/Ui/Form/FormBuilder.php(202): Anomaly\\Streams\\Platform\\Ui\\Form\\FormBuilder->build('2')
#26 /Users/me/dev/pyro/vendor/anomaly/streams-platform/src/Ui/Form/FormBuilder.php(287): Anomaly\\Streams\\Platform\\Ui\\Form\\FormBuilder->make('2')
#27 /Users/me/dev/pyro/core/anomaly/comments-module/src/Http/Controller/Admin/CommentsController.php(50): Anomaly\\Streams\\Platform\\Ui\\Form\\FormBuilder->render('2')
#28 [internal function]: Anomaly\\CommentsModule\\Http\\Controller\\Admin\\CommentsController->edit(Object(Anomaly\\CommentsModule\\Comment\\Form\\CommentFormBuilder), '2')
#29 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#30 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('edit', Array)
#31 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Anomaly\\CommentsModule\\Http\\Controller\\Admin\\CommentsController), 'edit')
#32 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#33 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Router.php(645): Illuminate\\Routing\\Route->run()
#34 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#35 /Users/me/dev/pyro/core/anomaly/users-module/src/Http/Middleware/AuthorizeRoutePermission.php(107): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Anomaly\\UsersModule\\Http\\Middleware\\AuthorizeRoutePermission->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /Users/me/dev/pyro/core/anomaly/users-module/src/Http/Middleware/AuthorizeControlPanel.php(51): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Anomaly\\UsersModule\\Http\\Middleware\\AuthorizeControlPanel->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /Users/me/dev/pyro/core/anomaly/users-module/src/Http/Middleware/AuthorizeModuleAccess.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Anomaly\\UsersModule\\Http\\Middleware\\AuthorizeModuleAccess->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /Users/me/dev/pyro/core/anomaly/users-module/src/Http/Middleware/AuthorizeRouteRoles.php(106): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Anomaly\\UsersModule\\Http\\Middleware\\AuthorizeRouteRoles->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /Users/me/dev/pyro/core/anomaly/users-module/src/Http/Middleware/CheckSecurity.php(86): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Anomaly\\UsersModule\\Http\\Middleware\\CheckSecurity->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /Users/me/dev/pyro/vendor/anomaly/streams-platform/src/Http/Middleware/ApplicationReady.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Anomaly\\Streams\\Platform\\Http\\Middleware\\ApplicationReady->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /Users/me/dev/pyro/vendor/anomaly/streams-platform/src/Http/Middleware/SetLocale.php(88): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Anomaly\\Streams\\Platform\\Http\\Middleware\\SetLocale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /Users/me/dev/pyro/vendor/anomaly/streams-platform/src/Http/Middleware/PoweredBy.php(38): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Anomaly\\Streams\\Platform\\Http\\Middleware\\PoweredBy->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /Users/me/dev/pyro/vendor/anomaly/streams-platform/src/Http/Middleware/VerifyCsrfToken.php(108): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Anomaly\\Streams\\Platform\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#61 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#62 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#63 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#64 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#65 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#66 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Router.php(647): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#67 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Router.php(622): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#68 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Router.php(588): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#69 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Router.php(577): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#70 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#71 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#72 /Users/me/dev/pyro/vendor/anomaly/streams-platform/src/Http/Middleware/SetLocale.php(88): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#73 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Anomaly\\Streams\\Platform\\Http\\Middleware\\SetLocale->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#76 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#77 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#78 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#79 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#80 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#81 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#82 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#83 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#84 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#85 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#86 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#87 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#88 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#89 /Users/me/dev/pyro/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#90 /Users/me/dev/pyro/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#91 {main}
"} 

```
#### Question / Suggestion:

Also, is it possible to show which subject the comment is made on? I mean since the comments are poly is it possible to see that each comment is made on which page or post or stream?

**Comment by RyanThompson** [comment]
Yes I plan on adding that in the control panel table

That said - is your relationship setup correctly in the DB? You have a subject_type and subject_id?

And this is clicking on view in backend right? 

Would you mind digging around a little here: https://github.com/anomalylabs/comments-module/blob/1.0/src/Http/Controller/Admin/CommentsController.php#L67

**Comment by Youhan** [comment]
The `view` problem was on my side but the `edit` problem still exists.

In the CommentsController we have
```
public function edit(CommentFormBuilder $form, $id)
{
        return $form->render($id);
}
```
and the CommentFormBuilder gets the `subjectId`: https://github.com/anomalylabs/comments-module/blob/1.0/src/Comment/Form/CommentFormBuilder.php#L174

In the table `subject_id` is 7 and `subject_type` is `Anomaly\PostsModule\Post\PostModel`
but in the CommentFormBuilder above (#L174) the `dd($this)` returns:
```
CommentFormBuilder {#1813 ▼
  #channel: "default"
  #subject: null
  #subjectId: null
  #subjectType: null
  #skips: array:9 [▶]
  #actions: array:1 [▶]
  #options: array:1 [▶]
  #assets: array:2 [▶]
  #ajax: false
  #handler: null
  #validator: null
  #repository: EntryFormRepository {#1905 ▶}
  #model: "Anomaly\CommentsModule\Comment\CommentModel"
  #entry: "2"
  #fields: array:1 [▶]
  #rules: []
  #buttons: []
  #sections: []
  #save: true
  #readOnly: false
  #form: Form {#1814 ▶}
  #callbacks: []
}
```

**Comment by RyanThompson** [comment]
We need different forms for backend and front end. I'll take care of it thanks for checking it out!

**Comment by Piterden** [comment]
Let's take Vue for the back part

**Comment by Youhan** [comment]
@RyanThompson I just came to say that the backend form should be separate, and now that you already said that I probably should delete this comment but the backspace key on my keyboard is not working ^_^
