### ISSUE TITLE
Error templates fail to render after updating to PyroCMS 3.7

### ISSUE THREAD

**Issue by bedomarci** [pyrocms/pyrocms#4970]
In case of any HTTP error, pyro tries to render a non existing error page. It caouses more error.
I added no override to my service provider. It appeared right after updating to Pyro 3.7

To reproduce I put a fake error anywhere: `throw new Exception()`

It supposed to show a 500 error. Rendered from default streams template. Than it gives me browser default 500 error.
In logs I get thousands of lines of error log. The first few lines are reporting the exception I added. Than it goes into a loop because not finding the template in accelerant theme, so i get this error for million times:

```
[2019-05-09 10:51:35] local.ERROR: Error loading pyrocms.theme.accelerant::errors.500: Template "pyrocms.theme.accelerant::errors.500" is not defined. {"user":1,"email":"bedomarci@gmail.com","url":"http://jamtravel.localhost/admin/jamtravel/partners/create","identifier":"c3523eb4-f2ba-479c-a156-b8363f624e68","exception":"[object] (InvalidArgumentException(code: 0): Error loading pyrocms.theme.accelerant::errors.500: Template \"pyrocms.theme.accelerant::errors.500\" is not defined. at D:\\Develope\\JAMTravel\\vendor\\anomaly\\streams-platform\\src\\View\\Twig\\Compiler.php:95, Twig_Error_Loader(code: 0): Template \"pyrocms.theme.accelerant::errors.500\" is not defined. at D:\\Develope\\JAMTravel\\vendor\\twig\\twig\\lib\\Twig\\Loader\\Chain.php:86)
[stacktrace]
#0 D:\\Develope\\JAMTravel\\vendor\\anomaly\\streams-platform\\src\\View\\Twig\\Engine.php(88): Anomaly\\Streams\\Platform\\View\\Twig\\Compiler->load('pyrocms.theme.a...')
#1 D:\\Develope\\JAMTravel\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(142): Anomaly\\Streams\\Platform\\View\\Twig\\Engine->get('pyrocms.theme.a...', Array)
#2 D:\\Develope\\JAMTravel\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(125): Illuminate\\View\\View->getContents()
#3 D:\\Develope\\JAMTravel\\vendor\\laravel\\framework\\src\\Illuminate\\View\\View.php(90): Illuminate\\View\\View->renderContents()
#4 D:\\Develope\\JAMTravel\\vendor\\laravel\\framework\\src\\Illuminate\\Http\\Response.php(42): Illuminate\\View\\View->render()
#5 D:\\Develope\\JAMTravel\\vendor\\symfony\\http-foundation\\Response.php(202): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#6 D:\\Develope\\JAMTravel\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ResponseFactory.php(55): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View), 500, Array)
#7 D:\\Develope\\JAMTravel\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\ResponseFactory.php(81): Illuminate\\Routing\\ResponseFactory->make(Object(Illuminate\\View\\View), 500, Array)
#8 D:\\Develope\\JAMTravel\\vendor\\anomaly\\streams-platform\\src\\Exception\\ExceptionHandler.php(112): Illuminate\\Routing\\ResponseFactory->view('streams::errors...', Array, 500, Array)
#9 D:\\Develope\\JAMTravel\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(289): Anomaly\\Streams\\Platform\\Exception\\ExceptionHandler->renderHttpException(Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#10 D:\\Develope\\JAMTravel\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Exceptions\\Handler.php(188): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#11 D:\\Develope\\JAMTravel\\vendor\\anomaly\\streams-platform\\src\\Exception\\ExceptionHandler.php(85): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#12 D:\\Develope\\JAMTravel\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(83): Anomaly\\Streams\\Platform\\Exception\\ExceptionHandler->render(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#13 D:\\Develope\\JAMTravel\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(55): Illuminate\\Routing\\Pipeline->handleException(Object(Illuminate\\Http\\Request), Object(InvalidArgumentException))
#14 D:\\Develope\\JAMTravel\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#15 D:\\Develope\\JAMTravel\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#16 D:\\Develope\\JAMTravel\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#17 D:\\Develope\\JAMTravel\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 D:\\Develope\\JAMTravel\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#19 D:\\Develope\\JAMTravel\\vendor\\anomaly\\streams-platform\\src\\Http\\Kernel.php(121): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#20 D:\\Develope\\JAMTravel\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Anomaly\\Streams\\Platform\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#21 D:\\Develope\\JAMTravel\\public\\index.php(56): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#22 {main}
"} 
```

I also debuged this line>` #8 D:\\Develope\\JAMTravel\\vendor\\anomaly\\streams-platform\\src\\Exception\\ExceptionHandler.php(112)`
At this point it succesfully renders the proper template and returns with expected response.

How to resolve this malfunctioning?
Where does **pyrocms.theme.accelerant::errors.500** come form?

**Comment by RyanThompson** [comment]
Hmm, where does it come from indeed. Are you fully updated? Seems like an old view override attempt.
